### ISSUE TITLE
Test better: DT address -> did

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/df-py#12]
**Motivation**

In Ocean, one can compute a "did" from a datatoken address. We do so in DF, because we need to (a) identify whether an asset is in purgatory (b)  output pool urls, and (c) maybe more. 

It's implemented in `util/oceanutil.py::calcDID()`.

However, I'm (Trent) not 100% confident in the implementation, because it was a hasty copy-and-paste from snippets of code in ocean.py (and aquarius?). 

The aim of this issue is to test calcDID() better.

**TODOs**

- [ ] Create 4+ "golden" mappings from datatoken --> did, using Aquarius directly. "Golden" means it's data that we really trust. To get that data, perhaps leverage Aquarius that's running in barge, or Aquarius running for V4 testing. Be sure to gather data for >1 chain. 
- [ ] Write unit tests for the golden mappings. Be sure to test for >1 chain.
- [ ] Run tests. If any failures, fix the implementation until no more failures.

**Notes**

Below was correspondence of Trent & Calina, when Trent started to write the implementation.

_Trent:_

I'm working on Data Farming. As part of it, I need to convert a datatoken address (with a chainid) to a did.
- I found an implementation of it in [ocean.py::ocean_assets.py](https://github.com/oceanprotocol/ocean.py/blob/cb1f6d16e0a9d53aa6f2509714f59bd86df622c9/ocean_lib/ocean/ocean_assets.py#L380). I've [implemented](https://github.com/oceanprotocol/df-py/blob/b62ee47a6dd53ba1e9ff58d733b143e97dede807/util/oceanutil.py#L272) it like that.
- I want to be able to test my implementation. I couldn't find anything simple in [test_ocean_assets.py](https://github.com/oceanprotocol/ocean.py/blob/v4main/ocean_lib/ocean/test/test_ocean_assets.py). But maybe I missed it, do you know of anything there?
- Or perhaps there are tests somewhere in the Aquarius repo, do you know?

Thanks in advance! 

----
_Calina:_

There's a make_did function in aqua, also in provider and ocean.py I think

And the testing is implicit, I.e. It wouldn't pass validation unless the did was valid

https://github.com/oceanprotocol/aquarius/blob/282a4aea5188b96c4969677cd4a5e5396b7b3c6e/aquarius/ddo_checker/shacl_checker.py#L91
```python
if not make_did(nft_address, str(chain_id)) == dict_orig.get("id"):
```
something like this?

and the test itself:
https://github.com/oceanprotocol/aquarius/blob/282a4aea5188b96c4969677cd4a5e5396b7b3c6e/tests/test_ddo_checker_shacl.py#L98
```python
valid, errors = validate_dict(_copy, 1234, json_dict["nftAddress"])
```

and if you look in the sample files, you’ll see we hardcoded dids to make sense for the dummy addresses and the ganache chainId
