### ISSUE TITLE
Support >1 basetoken, so rewards for H2O pools

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/df-py#15]
**Motivation**

Right now, the script only (a) measures OCEAN stake, measures (b) consume volume denominated in OCEAN, and (c) rewards accordingly.

We also need it to (a) measure H2O stake [& other approved tokens], (b) measure consume volume denominated in H2O [& other approved tokens], and (c) reward accordingly.

Notes:
- #13 needs to measure stake & volume across >1 chains 
- #27 needs to use measures for token collaborators. It will need to filter by (1) chainid (2) data nft address (3) where data is stored, eg Arweave or Filecoin

**TODOs**

- [x] Design / draw a flow diagram that handles data in _this_ issue, issue 13, and issue 27. Incorporate intermediate CSVs. (Result is in first comment below)
- [x] Refactor: rename "rewards.csv" to "rewards-OCEAN.csv". [#27](#27) will do the rest
- [x] Refactor: create intermediate csvs, for each NETWORK (see [first comment](https://github.com/oceanprotocol/df-py/issues/15#issuecomment-1088446644) below):
  - "stakes-{NETWORK}.csv" 
  - "pool_vols-{NETWORK}.csv"
- [x] Refactor: intermediate csvs also remember their basetokens
- [x] `calcRewards()` works off USD values for amount staked and volume, rather than OCEAN (& H2O) values
- [x] dftool adds a new step `getrate` to get exchange rate, and store it in OCEAN-rate.csv, H2O-rate.csv, etc 
- [x] Implement `getrate.py::getrate(token_symbol, start, fin, num_samples, seed)`, using coingecko. Include unit tests
- [x] Fix queries, unittests are failing
