### ISSUE TITLE
Test bounding rule further (APY, wash consume)

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/df-py#150]
**Bounding rules**

For a given week, the OCEAN rewarded is bounded by:

1. OCEAN budget for that week. E.g. for DF Alpha, this is 10K per week
2. APY bounded to ≤ 125%; therefore WPY of 1.57171%.
3. Ensuring that wash consuming is unprofitable.

**Implementation**
Implementation of the above includes:

1. Total OCEAN rewards distributed for that week = min(OCEAN_budget_week, total_staked * WPY)
2. APY ≤ 125% for each LP at each pool
3. 3% consume fee that goes to the Ocean community
4. And more.

**Scenario 1**

- 1 pool
- 1 staker, of 10K OCEAN
- 1 consume. Token was bought for 1 OCEAN
- 10K OCEAN rewarded

What's staker's APY?

**Scenario 2**

Start with scenario 1, then add add 1 new pool, 1 staker, of 10K OCEAN. Do 10 wash consumes. Token was bought for 1 OCEAN

What is APY of first staker and of new staker?

**Wash consume concern**

Limit of OCEAN rewarded is not currently a function of # consumes. So wash consuming can happen?

**TODOs**

- [ ] Test scenario 1 in Gsheet, py, or both. Fix as needed
- [ ] Test scenario 2 in Gsheet, py, or both. Fix as needed
- [ ] Ensure: APY ≤ 125% for each LP at each pool. I'm pretty sure it's not this. Write test, confirm, fix as needed
- [ ] Test "wash consume concern" in py. Fix as needed

**Comment by w1kke** [comment]
It seems I really misunderstood the formula as I thought this was already take care of.

From my point of view the formula that would solve this problem would take the community % into regard and limit each pool's reward via that. I also aimed at this in my question in the AMA but I did not get my point across.

In scenario 1 the maximum reward would be 1 $OCEAN * 0.03 = DCV * community % fee = 0.03 $OCEAN reward for the LP or  - thus it would be very, very low and basically all tokens would be returned to the pool. So 9999.97 $OCEAN would go back to the data farming rewards pool.
Scenario 2 would be exactly the same.
So in scenario 3 there would be 1 $OCEAN * 0.03 = DCV(1) * community % fee reward for LP of pool 1 and the same for pool 2. 9999.94 $OCEAN go back.
In scenario 4 there would be 9 $OCEAN * 0.03 =  DCV(1) * community % fee = 0.27 $OCEAN reward for LP of pool 1. And 0.03 $OCEAN for LP of pool 2.

This takes care of the wash consume problem but also drastically lowers the amount of rewards distributed. REAL consume has to happen of 10.000 $OCEAN = DCV(total) * community % fee to distribute all the $OCEAN reserved for this phase.

**Comment by trentmc** [comment]
New thought re wash consuming: 

what if we *didn't* change the reward function? That is, keep it as it is for DF1 and DF2.

Then, yes there will likely be wash consuming, but it's an evolutionary arms race for DCV, and the biggest winners will be the LPs who have *real* volume and don't have to wash consume as much to max out rewards.

**Comment by trentmc** [comment]
https://twitter.com/trentmc0/status/1540393775155089411?s=21&t=PTccjS551Ddd_HpdX2BlXQ

**Comment by trentmc** [comment]
Closing for now, given the current thinking in my comment above. Will reopen if needed.
