### ISSUE TITLE
modRates makes address uppercase, should be lowercase

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/df-py#171]
This is all in cleancase.py. 

The goal of cleancase.py is to ensure that:
- **addresses** are always in **lowercase**, and 
- **symbols** are always fully in **uppercase**. Otherwise we miss keys and things look empty.

Throughout the system, `rates` used to be a dict that keyed on `basetoken_symbol`. Accordingly, `cleancase.modRates()` made ensured keys are uppercase.

But we saw a risk: potential for conflicting keys if >1 tokens had the same symbol. Much safer to key on `basetoken_address` (not symbol) for data flowing through the system. So, this got changed, maybe 3-4 weeks ago. 

The problem is: in that change, `modRates()` did not get updated accordingly. It still thinks it's modifying for symbols (uppercase) when it really should be modifying for addresses (lowercase). Same for `assertRates()`. And maybe more. 

This means that some dicts may get emptied out after applying this filter. Definitely not good :(

Here is `modRates()`:
```python
def modRates(rates: dict) -> dict:
    """rates - dict of [basetoken_symbol] : USD_per_basetoken"""
    rates2 = {}
    for basetoken, rate in rates.items():
        basetoken2 = basetoken.upper()
        rates2[basetoken2] = rate

    assertRates(rates2)
    return rates2
```

**TODO for this issue**

- [x] Ensure that `modRates()` and `assertRates()` modify for addresses (lowercase), and are documented accordingly
- [x] Review the rest of cleancase, see if any issues with other datasets
- [x] Review other changes made in the switch from key-by-symbol to key-by-address, see if other things were missed

**Comment by trentmc** [comment]
Fixed in commit https://github.com/oceanprotocol/df-py/commit/2375b03befcb54714e1423b9e2beb93473c6efe3 as part of PR https://github.com/oceanprotocol/df-py/pull/166
