### ISSUE TITLE
Bound max APY locally, not just globally

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/df-py#206]
**Motivation**

Right now max APY is only enforced on a global scale: total rewards given out are limited by total staked.

But we could - and should - enforce max APY on a local scale, at pool or LP level. 

Does this matter? Yes, since we're seeing LPs get rewards >> APY. Not doing it locally should be seen as a _bug_ in our implementation. Examples: (ht [Alex slack thread](https://oceanprotocol.slack.com/archives/C026BNFH6HK/p1657085334296909))

- "I could stake 10 Ocean in a new dataset, but have a consume volume of 2200  (then I will get 50% of DF Rewards) -> crazy APR  (5000 Ocean reward for 10 staked)"
- "Bitcoin Historical Price Data".    According to consume percentage, they should get 3379 OCEAN (Had 721 ocean consumed from a total of 2135 and DF reward=10K Ocean).  But since liquidity is 11090, with enforced max APR, they should only get 266.59   (numbers will change when the average liquidity over 500 snapshots is computed, but you get my point)
- "Ethereum Historical Price Data" will take 3547.404565542935 as rewards (had 757.3712417852  consumes from a total of 2135 ), but with APR enforcing and current liquidity, they should only get 76.798 as rewards (totalLiquidity 3194.83129 * (125/52/100) (max APR). So, what is going to happen with the difference (3547.40 - 76.798) ?

**TODO**

- [ ] Write unit tests for rewards calc that capture the essence of the problem (eg from examples)
- [ ] Write the code to fix it, to make unit tests pass. Eg cap at pool level then LP level. 
- [ ] Confirm it: use dftool to calc rewards over the last week (Jun 30 - today Jul 6), and see if it fixes the issues in the datasets given above
- [ ] Merge it in
- [ ] Tweet "bug fixed: __"

**On overflows**

Q: What happens with overflows? they get redirected to another round, or we re-assign them to current round (is: some assets will get more rewards then the one computed only based on consume percentage)

A:

If there's just one pool, then overflow would go back to treasury, like it does now.

If there are >1  pools, excess from one pool would be directed to others. Overflow after that goes to treasury.

The main point is to respect the bounds, not just at global level but at local.
