### ISSUE TITLE
Test queries better

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/df-py#28]
**Background**

Current, test_queries is a bit of a blunt instrument, it grabs a huge amount off the chain and just checks that there are _some_ pools. I did it like that because I was fighting with getting subgraph to give me just the most recent results (it would always come back empty).

Also, I only tested for OCEAN, not for H2O, because that wasn't a token address.

**TODOs**:
- [x] Make query.py independent of approved_tokens. Stakes and vols csvs have all tokens, not just OCEAN and H2O. Test accordingly.
- [x] figure out how to get subgraph to give most recent results. Answer: sleep() and re-loop
- [x] get some tests for non-OCEAN tokens. Eg create a new token and test it
