### ISSUE TITLE
Output csvs to help LPs identify whether a pool qualifies for DF rewards

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/df-py#37]
**Overall goal:**
Have a CSV file or (files) that lists eligible pools, or something automatic in Ocean Market. This will be used by the frontend, see [df-issues#55](https://app.zenhub.com/workspaces/data-farming-60ddbf267dd0b500137f3c3d/issues/oceanprotocol/df-issues/55)

LPs should be able to see this easily.

Put into the CSV:

- What poolvols-chainx.csv has, derived from poolvols_at_chain:
  - chainid
  - basetoken (basetoken symbol)
  - pool_addr
  - vol_amt (total DCV)
- An aggregation of what stakes-chainx has, derived from stakes_at_chain:
  - stake_amt (total staked)
- Other key info:
  - nft_addr
  - DT_addr
  - DT_symbol
  - basetoken_addr
  - did
  - url - eg https://v4.market.oceanprotocol.com/asset/did:op:8d797a40e75a73a9646e48cfb14d5c0f6afb3c897f53403d00787b00e736b9f3

**Thoughts on design:**
- Should reconcile with existing [Data Flows](https://docs.google.com/presentation/d/11Nu_emSgw3iYZKDcmnvZC_aOM00MDyYTtTWQP4PYox4/edit#slide=id.p).
- `getPoolVols()` creates `poolvols-chainx.csv` which has: basetoken, pool_address, vol_amount. Q: Should we simply extend this csv? A: No; it's meant to be small and compact, just enough info for "dftool calc"
- `getStakes()` also finds the info about pool stake that this github issue is seeking. Should we extend it? A: No; it's meant to be small and compact, and actually it has stake info _per_ _LP_ which is more detail than this github issue seeks

**Chosen design:**
- Have a new file "poolinfo-chainx.csv". 
- How: query.query() already computes {pools list (of SimplePool), poolvols dict, stakes dict}. Currently it only saves csvs for poolvols and stakes. The trick is: also output a csv for pools, that takes info from {pools, poolvols, stakes).
- This was a simple tweak to the "Data Flows" diagram. And building was simple - just mostly two new commands in csvs.py.

Then, we want to easily compute these across all the chains, with one command. How:
- Add "dftool querymany" command, where several CHAINIDs are given. So it outputs one "poolinfo-chainx.csv" for each CHAINID.
- Then a simple bash-level "cat" command can concatenate "poolinfo-chain*.csv" into a single file like "poolinfo-all.csv". (Or we could put this into the tail end of "dftool querymany" to make it automatic. TBD.

**TODOs**
- [x] Write "dftool querymany" and tests. Get tests passing.
- [x] In csvs.py, write savePoolinfoCsv(), poolinfoCsvFilename(). In test_csvs.py, write tests. (Skip them passing for now.)
- [x] In chainlist.py, enable to compute subgraph from chainID. Write tests; get them passing.
- [x] In query.py, refactor: change from function args from using "subgraph" to "chainID". Calc subgraph JIT using info in constants.py. 
- [x] In oceanutil.py:calcDID(), make it a function of chainID. Write tests; get them passing. This is easy now, due to previous steps
- [ ] Get all tests passing
