### ISSUE TITLE
Near-term RF tuning: (1) DCV-bound at asset level, (2) allocate on dataset rank, (3) publishers get 2x

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/df-py#403]
_(Note: this was originally in [df-private#35](https://github.com/oceanprotocol/df-private/issues/35). I copied it here, now that it's going to implementation. I didn't transfer because gh doesn't allow transfer from private -> public repos.)_

### Motivation

Issue [df-private#22](https://github.com/oceanprotocol/df-private/issues/22) is the top-level EPIC/issue for Data Farming Reward Function (RF) design. We use it to explore candidate ideas to fix various issues (stake whales, etc). It sometimes has sub-tasks for sub-issues like "publisher incentives" ([df-private#30](https://github.com/oceanprotocol/df-private/issues/30)).

We like to lump RF updates into groups for release, so that it's easier for our community to track.

Recent iterations have led to a group of three candidate changes. Call them (1)(2)(3). They're all pragmatic, and don't introduce new issues (eg Sybil).

Aim of this issue: implement the three candidate changes, and get it released

### TODOs

- [x] Implement the items into a PR [here](https://github.com/oceanprotocol/df-py/pull/404)
  - [x] Implement (1): DCV-bound rewards at asset level, rather than global. Details below.
  - [x] Implement (2): Rather than allocate to datasets on DCV, allocate according to rank. Details below.
  - [x] Implement (3): Whatever the publisher has staked on the asset that they published, when we calculate rewards for them, it's as if they have 2x the stake. Details below.
  - [x] For (2): do plots and give recommended params. **[RF Ranking Study](https://docs.google.com/presentation/d/1zZdWfywruMPt6r7vfl0nQD8Fgj4wkfuMslZcWJmy3GE/edit#slide=id.p)**
- [x] Agree on a release date with the team. (Best to wait until implementation is done)
- [x] Prepare draft content
  - [x] Write draft blog content on "why and how of RF updates"
  - [x] Write draft tweetstorm
- [x] At appropriate time, roll out changes
  - [x] Merge the PR 
  - [x] Publish draft "why and how of RF updates" into relevant DF blog
  - [x] Publish draft tweetstorm
- [x] Write github issue for getting (3) shipped. Includes changes to backend, to frontend, and blog posts content. (The PR merged as part of *this* issue gets most of the way for the backend. So just some final work left.)

### Details on (1): DCV-bound rewards at asset level

DCV-bound rewards at asset level, rather than global.

Background: In [df-py#357](https://github.com/oceanprotocol/df-py/issues/357) [[commit](https://github.com/oceanprotocol/df-py/commit/3816d66d9309439410dd5d6037e06d314c105996)] [[PR](https://github.com/oceanprotocol/df-py/pull/360)], we implemented "bound total rewards by total DCV * mult". It was rolled out in DF Round 9 (DF9). It's a key building block to stopping wash consume.

The idea here is: rather than bounding _total_ rewards by DCV (global), bound them at the _asset_ level. (Similar to how we bound to <= 125% APY at asset level.)

Updated macro algorithm for DF rewards distribution:
- As usual, distribute rewards pro-rata to each asset on its DCV.
- Then, for each asset:
  - Compute rewards
  - Further bound rewards to the asset by its DCV * mult; and by 125% APY

Benefits: 
- People can't rely on a single actor to do wash consume for everyone; instead they need to do it themselves. This catalyzes more engagement from more people
- More robust RF, because it's specific to each asset: generalizing on the previous point, it likely bound other undesirable behaviors that we haven't yet identified
- Conceptually simpler implementation, side-by-side with 125% bounding

### Details on (2): Allocate to datasets on rank

Rather than allocate to datasets on DCV, allocate according to rank.

Implementing this will raise Q's about how much % to give to rank 1, rank 2, etc. E.g. is it 10% to rank 1, 9% to rank 2, etc. There are many options here. Here's how we'll approach it:
- build it, and parameterize the problem
- make 2-3 proposals of parameter settings (with data/plots). Leverage heuristics like "give 99% of rewards to top 20 datasets" or "rank 1 dataset should get <= 10% reward"
- review with everyone, and select one

### Details on (3): 2x to publishers

Whatever the publisher has staked on the asset that they published, when we calculate rewards for them, it's as if they have 2x the stake." 

- Make it where: whatever the publisher has staked on the asset that they published, when we calculate rewards for them, it's as if they have 2x the stake.
- Pro: simple to implement, simple to explain
- Con: incentivizes fraudulent publishing + wash consume. This will go away when DCV_mult hits 0.03.

Note: this is Cand E in [df-private#30](https://github.com/oceanprotocol/df-private/issues/30)).

Open Q: is 2x the best? Or should we go higher, e.g. 5x to really drive incentive to publish?

**Comment by trentmc** [comment]
> Make the MAX_N_RANK_ASSETS elastic (adjust to # assets w/ DCV > 0)

FYI already does this, up to its limit. Eg if you set it to 100, and there are only 20 assets with DCV > 0, then it behaves as if its value is 20.

If you want it to be 100% adaptive, then make its value to be super-large (eg 1M).

> Let's ship, measure, and focus on where we can move the fundamentals

Yes. Let's ship.

**Comment by trentmc** [comment]
This cannot be closed until all the tasks in it are done.

The non-code tasks of this issue are not done yet. 

See the description at the top four details.

**Comment by trentmc** [comment]
@idiom-bytes and I see a revert. What is it about? More context please

**Comment by alexcos20** [comment]
well, it was merged before end of round 22 :)  ->  round 22 will use ranked allocation, which is not the case
Reverted and will be merged again tomorrow morning, so it will be applied starting from round 23

**Comment by trentmc** [comment]
> well, it was merged before end of round 22 :) -> round 22 will use ranked allocation, which is not the case Reverted and will be merged again tomorrow morning, so it will be applied starting from round 23

Thanks for the update! That makes sense. I just didn't have context.

**Comment by trentmc** [comment]
>  closed this as completed in 8873dce 1 hour ago

This github issue is not closed until _all_ of the items in it are done. Code is just one part. See the description at the top for the checklist.

Re-opening.

**Comment by idiom-bytes** [comment]
@trentmc we are closing this as all items above have been completed.

New tickets will be generated for each new issue discovered.
