### ISSUE TITLE
"dftool query" and "dftool dispense" need more specific names

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/df-py#411]
### Background / motivation

In dftool, CLI includes:
```text
  dftool query ST FIN NSAMP CSV_DIR CHAINID - query chain, get (symbols, vols)
  dftool allocations ST FIN NSAMP CSV_DIR CHAINID
  dftool vebals ST FIN NSAMP CSV_DIR CHAINID
...
  dftool dispense CSV_DIR [CHAINID] [DFREWARDS_ADDR] [TOKEN_ADDR] - from rewards, dispense funds
  dftool dispense_passive CHAINID AMOUNT
```

The first 3 commands are about querying info from the chain
- symbols and volumes
- allocations
- vebals

The last two commands are about dispensing funds
- active
- passive

The problems:
- The first query command (`dftool query`) doesn't distinguish _what_ it's querying and returning. Same for the function it calls (`dftool::do_query()`).
- The first dispense command (`dftool dispense`) doesn't distinguish whether it's passive or active. Same for the function it calls (`dftool::do_dispense()`).

### TODO for this issue

- [x] Update ["flows" GSlides](https://docs.google.com/presentation/d/11Nu_emSgw3iYZKDcmnvZC_aOM00MDyYTtTWQP4PYox4/edit#slide=id.g148220d8488_0_0) 
- [x] (a) rename do_query() to do_volsim(); (b) Rename do_dispense() to do_dispense_active()
- [x] (a) add "dftool volsim" which calls do_volsim(); keep "dftool query" at this point. (b) add "dftool dispense_active" which calls do_dispense_active(); keep "dftool dispense" at this point.
- [x] in df-sql, df-webapp, github actions, or anywhere else that uses "dftool query", replace with "dftool volsim". Same for "dftool dispense" --> "dftool dispense_active"
- [x] once all of (3) is clearly working, then deprecate "dftool query" and "dftool dispense"

**Comment by idiom-bytes** [comment]
I have now deprecated those commands, and made updates to continue fixing commands and test coverage.
