### ISSUE TITLE
All test_query and test_thegraph unit tests are failing with brownie.exceptions.VirtualMachineError: revert

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/df-py#48]
**Describe the bug**

When running unit tests, everything passes except:
```text
FAILED util/test/test_query.py::test_queryAndCalcResults - brownie.exceptions.VirtualMachineError: revert
...
FAILED util/test/test_thegraph.py::test_thegraph_approvedTokens - brownie.exceptions.VirtualMachineError: revert
...
```

Detailed traceback is below.

**To Reproduce**

Follow README, to the point of running all tests:
```console
brownie test util
```

I'm also seeing this in #49. Consider solving _this_ issue a blocker to that issue.

**Expected behavior**
Everything should pass.

**TODOs for this issue**

- [x] Get most up-to-date barge. Maybe something changed that affected this
- [x] Copy most up-to-date Ocean v4 contracts code into here. Maybe something changed that affected this
- [x] Do tests pass now? If yes, stop. Else dig deeper. A: tests do not pass
- [x] Fix oceanutil.py, so it reflect changes in smart contracts. To help this, create new test_oceanutil.py
- [x] Ensure all tests passing

**More info**

Example traceback:
```console
(venv) trentmc@trentmcLnv:~/code/df-py$ brownie test util/test/test_query.py::test_queryAndCalcResults
Brownie v1.18.1 - Python development framework for Ethereum

==================================================== test session starts ====================================================
platform linux -- Python 3.8.10, pytest-6.2.5, py-1.11.0, pluggy-1.0.0
rootdir: /home/trentmc/code/df-py
plugins: eth-brownie-1.18.1, xdist-1.34.0, hypothesis-6.27.3, forked-1.4.0, web3-5.27.0
collected 1 item                                                                                                            

util/test/test_query.py F                                                                                             [100%]

========================================================= FAILURES ==========================================================
_________________________________________________ test_queryAndCalcResults __________________________________________________

ADDRESS_FILE = '/home/trentmc/.ocean/ocean-contracts/artifacts/address.json'
SUBGRAPH_URL = 'http://127.0.0.1:9000/subgraphs/name/oceanprotocol/ocean-subgraph'

    @enforce_types
    def test_queryAndCalcResults(ADDRESS_FILE, SUBGRAPH_URL):
>       _setup(ADDRESS_FILE, SUBGRAPH_URL, num_pools=2)

util/test/test_query.py:17: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
venv/lib/python3.8/site-packages/enforce_typing/decorator.py:29: in wrapper
    return func(*args, **kwargs)
util/test/test_query.py:81: in _setup
    conftest.randomDeployTokensAndPoolsThenConsume(num_pools)
venv/lib/python3.8/site-packages/enforce_typing/decorator.py:29: in wrapper
    return func(*args, **kwargs)
util/test/conftest.py:64: in randomDeployTokensAndPoolsThenConsume
    (DT, pool) = randomDeployPool(accounts[account_i])
venv/lib/python3.8/site-packages/enforce_typing/decorator.py:29: in wrapper
    return func(*args, **kwargs)
util/test/conftest.py:157: in randomDeployPool
    return deployPool(init_OCEAN_stake, DT_OCEAN_rate, DT_cap, pub_account)
venv/lib/python3.8/site-packages/enforce_typing/decorator.py:29: in wrapper
    return func(*args, **kwargs)
util/test/conftest.py:164: in deployPool
    (data_NFT, erc721_factory) = oceanutil.createDataNFT(
venv/lib/python3.8/site-packages/enforce_typing/decorator.py:29: in wrapper
    return func(*args, **kwargs)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

name = 'dataNFT', symbol = 'DATANFTSYMBOL', from_account = <Account '0xe2DD09d719Da89e5a3D0F2549c7E24566e947260'>

    @enforce_types
    def createDataNFT(name: str, symbol: str, from_account):
        erc721_factory = ERC721Factory()
        erc721_template_index = 1
        factory_router = factoryRouter()
        token_URI = "https://mystorage.com/mytoken.png"
>       tx = erc721_factory.deployERC721Contract(
            name,
            symbol,
            erc721_template_index,
            factory_router.address,
            ZERO_ADDRESS,  # additionalMetaDataUpdater set to 0x00 for now
            token_URI,
            {"from": from_account},
        )
E       brownie.exceptions.VirtualMachineError: revert
E       Trace step -1, program counter 379:
E         File "contracts/oceanv4/ERC721Factory.sol", lines 24-819, in None:    
E            *      New datatoken proxy contracts are links to the template contract's bytecode.
E            *      Proxy contract functionality is based on Ocean Protocol custom implementation of ERC1167 standard.
E            */
E           contract ERC721Factory is Deployer, Ownable, ReentrancyGuard {
E               using SafeERC20 for IERC20;
E               using SafeMath for uint256;
E               address private communityFeeCollector;
E               uint256 private currentNFTCount;
E               address private erc20Factory;
E               uint256 private nftTemplateCount;
E       
E               struct Template {
E                   address templateAddress;
E                   bool isActive;
```

Full traceback:
[traceback.txt](https://github.com/oceanprotocol/df-py/files/8668142/traceback.txt)
