### ISSUE TITLE
More thorough dftool command test coverage

### ISSUE THREAD

**Issue by idiom-bytes** [oceanprotocol/df-py#491]
### Background / Motivation

Related: [df-py#589](https://github.com/oceanprotocol/df-py/issues/589) "Make auto active rewards reliable". Reliability < 50%. Yet when we make changes to df-py, all tests pass.

Most dftool commands are tested to be called "at all" via the no-arguments-in "noarg" test. And some dftool commands are tested more thoroughly. 

Not all dftool commands _need_ thorough testing. That's overkill.

However, we _should_ have thorough testing for key dftool commands, that are are used in the rewards flows (vs just for manual debugging). For a list, simply see the ones in dftool's [HELP_SHORT](https://github.com/oceanprotocol/df-py/blob/32e6240f9e4f81b31e3ae39c712d3d323e8a358a/dftool#LL51C1-L51C11) variable. (HELP_LONG includes the rest.) The TODOs reflects this list.

### Tactic

If we run each test below thoroughly end-to-end, runtime will be too long, it will be hard to maintain, and in general it'll be overkill. 
- Re overkill: we already have unit test for each piece of functionality used by the dftool command
- And we already have end-to-end tests for dftool
- The main thing we need to test is: does it parse the arguments properly? Including optional params
- A better tactic: do like [test_dftool_challenge.py](https://github.com/oceanprotocol/df-py/blob/main/util/challenge/test/test_dftool_challenge.py). It passes in a special CSV_DIR to dftool; dftool detects that and bypasses the real work (while still parsing arguments etc). It also tests various combinations of optional parameters
- Recommend this as the baseline approach for the commands below. Though expect exceptions:)

### TODOs

Ensure each of the following has a thorough test.

- [ ] dftool compile
- [ ] dftool getrate
- [ ] dftool volsym
- [ ] dftool allocations
- [ ] dftool vebals
- [x] dftool challenge_data
- [x] (N/A, not built yet) dftool predictoor_data
- [ ] dftool calc
- [ ] dftool dispense_active
- [ ] dftool dispense_passive
- [ ] dftool nftinfo

**Comment by trentmc** [comment]
> test_noarg_commands was trying to provide coverage to many commands who were not properly getting tested.
> The following commands: volsym, getrate, ... chaininfo were in that list, but were likely not being properly tested because they all need arguments. Some commands (querymany) don't even exist anymore. Others such as dispense_active are visible but it's close friend dispense_passive is not.

Please allow me to correct this.

`dftool X` with no extra arguments goes to that method, and prints the help info for that command. It's worth testing. This is what `test_noarg_commands` does. It does this for _all_ the commands.

In slack @idiom-bytes had mentioned removing them ([in this PR](https://github.com/oceanprotocol/df-py/pull/490)) "because they were not doing anything". Incorrect, as mentioned in the paragraph above. I commented in the PR accordingly.

`test_noarg_commands` is _not_ trying to give full coverage for a given argument when there _are_ commands. (Hence the "noarg" in its name). That's the role of other tests in test_dftool.py.

`test_noarg_commands` probably does need refreshing however: add in new dftool commands, and remove obsolete ones.

There's an extra benefit to `test_noarg_commands`: currently this is the _only_ test for some dftool commands, to call the command's function in dftool `do_COMMAND()`. So at least there's _some_ coverage for the command. We _could_ write more thorough tests for each command, it's just a question of priority (and it wasn't a priority until now).

**Comment by trentmc** [comment]
> VM shell scripts are not in project, and are not being tested. ... Add coverage to shell scripts (all.sh and nftinfo.sh) that currently live in the VM

Random extra .sh scripts hurts maintainability. And, we already have a CLI with a nicely testable pattern: dftool, with test_dftool and then Python support modules (typically in util/*.py). I recommend that for here too. Specifically:
- Move the of all.sh and nftinfo.sh out of specialized .sh scripts, and into `dftool` with a new support python module below. 
- Then test the support python module directly. 
- And do a thin test to make sure that the dftool call works. 

This is the same recommendation that I gave for a proposed gen_hist_data.sh script, in [PR#396](https://github.com/oceanprotocol/df-py/pull/396).

**Comment by idiom-bytes** [comment]
@trentmc thank you for your comments
updated ticket

will also review current noargs implementation in PR to improve before merging

**Comment by trentmc** [comment]
Made high priority because our CI around active rewards is abysmal. Symptom: reliability of active rewards successfully running on a given week is <50%.

Doing this will help a lot.
