### ISSUE TITLE
[Predictoor DF] Ship MVP -- df-py portion

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/df-py#540]
### Background / motivation

Parent epic: [[Predictoor DF] Ship MVP](https://github.com/oceanprotocol/s3-pm/issues/65)
- _This_ issue is its df-py portion.

Related epic: [[Challenge DF] Ship MVP](https://github.com/oceanprotocol/s3-pm/issues/64)]
- And [here's its df-py portion](https://github.com/oceanprotocol/df-py/issues/539), and [related PR](https://github.com/oceanprotocol/df-py/pull/537)

### TODOs

- [ ] Review Challenge DF : df-py portion : related PR
- [ ] Either (a) create new branch, or (b) start working in "Challenge DF" branch
- [ ] Write prototype
- [ ] (If applicable) Merge code with "Challenge DF" branch
