### ISSUE TITLE
[Epic] Proper CI for VM that runs bash script with dftool --> consumption by df-sql

### ISSUE THREAD

**Issue by trizin** [oceanprotocol/df-py#587]
### Background / motivation

df-web (DF webapp) relies on df-sql for all data.

Right now there's a bash script sitting locally? on Berkay's machine, that he has manually put into a VM. df-sql asks the VM to run the script. The script runs df-py to grab data and create csvs. df-sql consumes these csvs, and then makes their data available for df-webapp via a REST API.

It's poorly tested, and poorly documented.  If we make even a simple change to dftool like moving to snake_case, and update tests in df-py CI, it'll still break this flow.

We need a means to make changes to df-py with impunity, knowing that it won't break df-sql.

### Potential tools 

When df-py/csvs.py loads a csv, it checks that each column has the proper label. It also does basic sanity check on columns with eth addresses.

df-sql README.md shows a basic flow

"Data Flow" GSlides linked from top of df-py README have basic flow

df-py bottom half has a bunch of stuff on devops & flows. Maybe useful? Right now it's verbose, and maybe largely obsolete? Super unclear.

### TODOs

- [x] Put the bash script that the VM runs into df-py repo
- [x] In df-py, document the flow to get the container running. Clean up README.md and related.
- [x] Have some way to CI verify that df-sql can run the bash script in df-py to successfully expose the REST API. Maybe: have df-py run the container, auto-insert the script, run the VM, and run df-sql's tests against it.

Lower priority. Do this when we add scripts to df-py:
- [ ] In df-py, have a CI test that (a) runs the script to create csvs, (b) re-loads it via util/csvs.py including running csv sanity checks

**Comment by calina-c** [comment]
I think we can close this, @trizin

**Comment by trentmc** [comment]
@trizin: "we can close this"
