### ISSUE TITLE
 Update predict-eth repo to reflect new nmse calcs; do new release

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/df-py#704]
### Background / motivation

df-py/df_py/challenge/nmse.py has `calc_nmse()` to calculate the nmse. (And and tests/test_nmse.py to test the results).

Issue [df-py#696](https://github.com/oceanprotocol/df-py/issues/696) was recently completed. It updated `calc_nmse()` by re-scaling things. Now, nmse values are more sane. (It doesn't affect winners.) 

### TODOs

- [ ] In predict-eth repo, update its separate implementation of `calc_nmse()`, to be in sync with the one in df-py
- [ ] Update predict-eth READMEs if needed
- [ ] Do a new release of df-py to pypi
