### ISSUE TITLE
Need thorough diagram for DF $ flow. Include Predictoor DF

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/df-py#727]
### Background / motivation

We have **[df-py GSlides](https://docs.google.com/presentation/d/15Zys9X5eLzlApqhobdGpn9SdGrFuKyr2W14D4dSSzgk/edit#slide=id.g12947cdad3a_0_11)** that include:
- "Data Flow" slide: flow of _information_ from each DF stream
- "Example csvs" slide: the schema for the information that's flowing
- "Calc rewards csvs/tables" slide: details on inputs & outputs for `calc_rewards()` function
- "From dfpy nftinfo to dfsql aggregate": details on how we get sql data to FE
- ["Fee Distributor" slide](https://docs.google.com/presentation/d/15Zys9X5eLzlApqhobdGpn9SdGrFuKyr2W14D4dSSzgk/edit#slide=id.g17c4630f0c1_0_0): flow of data and $ funds in DF, with focus on `FeeDistributor` and `FeeEstimate` contracts
- ["Macro $ flow" slide](https://docs.google.com/presentation/d/15Zys9X5eLzlApqhobdGpn9SdGrFuKyr2W14D4dSSzgk/edit#slide=id.g295c09f13fc_0_0): shows high-level $ flow from OPF 51% wallet --> vesting wallets --> splitter contract. (I just copied this slide from DF Main slides)

These GSlides are readily accessible, at the top of [df-py README](https://github.com/oceanprotocol/df-py/blob/main/README.md). That's good. Their main use is for us internally, for a common understanding of how the system works including specifics of data schema so that BE, SQL, and FE can talk to each other. 

Those slides have served us well. But now that we're going into Predictoor DF (counting starts Nov 9), an issue has become more apparent: documentation on DF $ flow isn't thorough enough. We've "got by" so far because it wasn't _that_ complex. But Predictoor DF adds complexity, with the addition of Oasis Sapphire network, OCEAN on Sapphire, and Oasis ROSE being part of DF rewards. 

We don't need to document it well for the community; they don't care enough. But we _do_ need to document it better for ourselves, to avoid errors and to minimize risk.

### TODOs

Macro:
- [ ] Taking ["Fee Distributor" slide](https://docs.google.com/presentation/d/15Zys9X5eLzlApqhobdGpn9SdGrFuKyr2W14D4dSSzgk/edit#slide=id.g17c4630f0c1_0_0) and ["Macro $ flow" slide](https://docs.google.com/presentation/d/15Zys9X5eLzlApqhobdGpn9SdGrFuKyr2W14D4dSSzgk/edit#slide=id.g295c09f13fc_0_0) as inputs, create a new slide that focusing on the flow of $ to answer the Q's below.

Be sure to include:
- [ ] **DF: Passive DF: OCEAN flow.**
- [ ] **DF: Active DF: Challenge DF: OCEAN flow.**
- [ ] **DF: Active DF: Volume DF: OCEAN flow.**
- [ ] **DF: Active DF: Predictoor DF: OCEAN flow.** 
- [ ] **DF: Active DF: Predictoor DF: ROSE flow.** Wrapped ROSE flows roughly as: (i) from Oasis' wallet to OPF wallet, (ii) to Predictoors who receive these rewards. Sub-questions that the diagram & accompanying text should answer: 
  - [ ] Is the (i) -> (ii) flow correct? If it's different (missing steps etc) please do the correct flow
  - [ ] For (i): what is the schedule for Oasis sending funds? (How much? At which days/times?)
  - [ ] For (i): how's it being sent? Potential A: manually, by Matej or a lieutenant
  - [ ] For (ii): what is the schedule for OPF sending funds? (How much? At which days/times? )
  - [ ] For (ii) how's it being sent? Eg is it a script, and if yes, what script specifically? Is it run as part of weekly DF ops github actions, or other?
  - [ ] How do we execute wrapped ROSE going from OPF wallet to Predictoors?
  - [ ] For (i)(ii): what's the OPF address on Sapphire that holds the funds? How's it controlled? Eg 1/2 multisig of Alex + Trent?

**Comment by trentmc** [comment]
> I've added the slide.
> 
> Please review [DF Weekly $ flow](https://docs.google.com/presentation/d/15Zys9X5eLzlApqhobdGpn9SdGrFuKyr2W14D4dSSzgk/edit#slide=id.g2a570ed45e2_0_0)

Looks good! 

FYI I moved it to earlier in the deck.

Closing.
