### ISSUE TITLE
Deprecate Challenge DF after Nov 30

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/df-py#733]
### Background / motivation

The final round of Challenge DF will be on DF65, which ends Nov 30, 2023. 

The epic is [df-private#63](https://github.com/oceanprotocol/df-private/issues/63) "Wind down Challenge DF". It has more context. This is a sub-issue. 

### TODOs for this issue

**Do soon (do not merge!)**
- [ ] In df-py repo, in a branch/PR: deprecate Challenge DF
  
**Do after DF66 is complete (Nov 30, 2023):**
- [ ] Merge df-py branch from above
- [ ] Create a new release

**Comment by trentmc** [comment]
> This must be done before DF67 concludes.

Thanks @trizin !

@calina-c you'll handle?
