### ISSUE TITLE
Wind down veOCEAN, Passive DF, Volume DF

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/df-py#830]
## Background / Motivation

Ref: "Superintelligence Alliance Updates to Data Farming and veOCEAN" blog [link](https://blog.oceanprotocol.com/superintelligence-alliance-updates-to-data-farming-and-veocean-68d7b29c5100)

This blog said that veOCEAN, Passive DF, and Volume DF would wind down in the event the ASI merger "yes" happened. The "yes" did happen.

And regardless, we _want_ to wind them down because they are not capital-efficient, especially compared to Predictoor DF.

## TODOs

- [ ] Do airdrop to veOCEAN holders
- [ ] Update DF web: (a) "Passive DF" tab: remove ability to lock / refresh OCEAN; update title/subtitle to "eg Passive DF has stopped. Details here (give link)." (b) "Volume DF tab": fully remove (c) "rewards" tab: remove all but "Predictoor DF" section. [#723](https://github.com/oceanprotocol/df-web/issues/723)
- [ ] Update docs.oceanprotocol.com, "Ocean Data Farming Series" blog, and "DF Main is here" blog
